baseURL = "/"
languageCode = "en-us"
title = "Robotix - IIT Hyderabad"
theme = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
  name = "Home"
  url = ""
  weight = 1

[[menu.nav]]
  name = "About"
  url = "about"
  weight = 2

[[menu.nav]]
  name = "Projects"
  url = "portfolio"
  weight = 3

[[menu.nav]]
  name = "Blogs"
  url = "blog"
  weight = 4

[[menu.nav]]
  name = "Events"
  url = "events"
  weight = 5

[[menu.nav]]
  name = "Resources"
  url = "https://docs.google.com/document/d/1sULk6FGBYPKWGM-C88B9Yos2nbrvWy9N5Z20Fu5MC1c/edit?tab=t.0"
  weight = 6

# Site Params
[params]
logo = "images/logo.png"
logo_footer = "images/logo-footer.png"
favicon_icon = "images/favicon.ico"
favicon_shortcut_icon = "images/favicon.png"
custom_stylesheets = [] # e.g., ["scss/my_1.scss", "scss/my_2.scss"]
dateFormat = "26 FEB 1994"

# Meta data
description = "Roxo Hugo themes | Design Agency Template by StaticMania"
author = "StaticMania"

# Google Analytics
googleAnalitycsID = "Your ID"

# Form Handling (using formspree.io)
fabform = "https://fabform.io/f/USAg2Jl"

# Banner Section
[params.banner]
enable = true
background_image = "images/backgrounds/home-background.png"
heading = "Striving to achieve perfection in the field of Robotics."
primary_button = "More About Us"
primary_button_url = "about"
secondary_button = "Recent Events"
secondary_button_url = "events"

# QR Print
qr_print = false

# Footer
[params.footer]
title = "Contact Info"
address = "IIT Hyderabad, Kandi, Sangareddy, Telangana, India"
phone = "+91 1234567890"
email = "robotix@iith.ac.in"

# Footer Sitemap
[sitemap]
title = "Sitemap"

[[sitemap.link]]
  name = "About"
  url = "about"

[[sitemap.link]]
  name = "Blogs"
  url = "blogs"

[[sitemap.link]]
  name = "Projects"
  url = "portfolio"

[[sitemap.link]]
  name = "Events"
  url = "events"

[[sitemap.link]]
  name = "Team"
  url = "team"

[[sitemap.link]]
  name = "Resources"
  url = "resources"

[[sitemap.link]]
  name = "Contact"
  url = "contact"

# Footer Social Media
[params.footer.social]
title = "Social Media"

[[params.footer.social.link]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/company/robotix-iith/"

[[params.footer.social.link]]
  name = "Facebook"
  url = "https://www.facebook.com/RoboticsClubIITH/"

[[params.footer.social.link]]
  name = "Instagram"
  url = "https://www.instagram.com/robotix.iith?igshid=YmMyMTA2M2Y%3D"

# Footer Service
[params.footer.service]
title = "We help brands:"
description = """
develop design solutions<br>
produce valuable cultural content<br>
create fresh brand experience
"""

# Back to Top
[params.footer.back_to_top]
description = "I want to <br> visit again"
